name: dwdb
description: A proxy between Chrome Debugger Protocol and the Dart VM Protocol

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^1.5.1
  path: ^1.6.2
  source_maps: ^0.10.8
  webkit_inspection_protocol: ^0.3.5

dev_dependencies:
  test: ^1.5.1



